CREATE TABLE IF NOT EXISTS public.staging_alunos_2026 (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    verificado boolean DEFAULT false,
    erro_importacao text,
    
    -- CSV Columns (All TEXT to avoid import errors)
    matricula_do_aluno text,
    situacao text,
    data_de_situacao text,
    data_de_realizacao text,
    tipo_de_transferencia text,
    motivo_da_transferencia text,
    codigo_inep_do_aluno text,
    nome_social_do_aluno text,
    nome_civil_do_aluno text,
    login_do_aluno text,
    procedencia_rendimento text,
    procedencia_escola text,
    procedencia_modalidade_curso text,
    cns_do_aluno text,
    cpf_do_aluno text,
    rg_do_aluno text,
    rg_do_aluno_orgao_expedidor text,
    rg_do_aluno_uf text,
    rg_do_aluno_data_de_emissao text,
    telefones_de_contato text,
    data_de_nascimento_do_aluno text,
    nis_do_aluno text,
    endereco_eletronico_do_aluno text,
    conta_do_google text,
    municipio_de_nascimento text,
    uf_de_nascimento text,
    sexo text,
    utiliza_transporte_escolar text,
    raca_cor text,
    possui_deficiencia text,
    possui_laudo_medico text,
    tipo_de_deficiencia text,
    recebe_atendimento_especializado text,
    tipo_de_atendimento_especializado text,
    recebe_bolsa_familia text,
    filiacao_1 text,
    cpf_da_filiacao_1 text,
    escolaridade_da_filiacao_1 text,
    profissao_da_filiacao_1 text,
    filiacao_2 text,
    cpf_da_filiacao_2 text,
    escolaridade_da_filiacao_2 text,
    profissao_da_filiacao_2 text,
    responsavel text,
    tipo_de_responsavel text,
    nome_do_responsavel text,
    login_do_responsavel text,
    cpf_do_responsavel text,
    data_de_nascimento_do_responsavel text,
    nis_do_responsavel text,
    endereco_eletronico_do_responsavel text,
    logradouro text,
    numero_do_logradouro text,
    bairro_do_logradouro text,
    complemento_do_logradouro text,
    municipio_do_logradouro text,
    distrito_do_logradouro text,
    uf_do_logradouro text,
    cep_do_logradouro text,
    numero_da_conta_de_energia text,
    latitude text,
    longitude text,
    localizacao_diferenciada text,
    rede_de_escolas text,
    codigo_da_escola text,
    nome_da_escola text,
    localizacao_zona text,
    etapa_de_ensino text,
    modalidade text,
    curso text,
    serie_etapa text,
    turno text,
    turma text,
    descricao_da_turma text,
    nome_do_programa text,
    tipo_da_turma text,
    turma_multietapa text,
    turma_multisseriada text,
    situacao_da_turma text,
    numero_da_sala text,
    codigo_do_anexo text,
    nome_do_anexo text,
    numero_da_matricula_do_modelo_novo_da_certidao text,
    nacionalidade text,
    remanescente_de_quilombo text,
    pertencente_ao_povo_cigano text,

    CONSTRAINT staging_alunos_2026_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

ALTER TABLE public.staging_alunos_2026 OWNER to postgres;
