-- Drop table if exists to ensure clean slate with new column names
DROP TABLE IF EXISTS public.staging_alunos_2026;

CREATE TABLE public.staging_alunos_2026 (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    verificado boolean DEFAULT false,
    erro_importacao text,
    
    -- Exact CSV Columns (All TEXT)
    "Matrícula do aluno" text,
    "Situação" text,
    "Data de situação" text,
    "Data de realização" text,
    "Tipo de transferência" text,
    "Motivo da transferência" text,
    "Código INEP do aluno" text,
    "Nome social do aluno" text,
    "Nome civil do aluno" text,
    "Login do aluno" text,
    "Procedência rendimento" text,
    "Procedência escola" text,
    "Procedência modalidade/curso" text,
    "CNS do aluno" text,
    "CPF do aluno" text,
    "RG do aluno" text,
    "RG do aluno - Órgão expedidor" text,
    "RG do aluno - UF" text,
    "RG do aluno - Data de emissão" text,
    "Telefones de contato" text,
    "Data de nascimento do aluno" text,
    "NIS do aluno" text,
    "Endereço eletrônico do aluno" text,
    "Conta do Google" text,
    "Município de nascimento" text,
    "UF de nascimento" text,
    "Sexo" text,
    "Utiliza transporte escolar" text,
    "Raça/Cor" text,
    "Possui deficiência" text,
    "Possui laudo médico" text,
    "Tipo de deficiência" text,
    "Recebe atendimento especializado" text,
    "Tipo de atendimento especializado" text,
    "Recebe Bolsa Família" text,
    "Filiação 1" text,
    "CPF da filiação 1" text,
    "Escolaridade da filiação 1" text,
    "Profissão da filiação 1" text,
    "Filiação 2" text,
    "CPF da filiação 2" text,
    "Escolaridade da filiação 2" text,
    "Profissão da filiação 2" text,
    "Responsável" text,
    "Tipo de responsável" text,
    "Nome do responsável" text,
    "Login do responsável" text,
    "CPF do responsável" text,
    "Data de nascimento do responsável" text,
    "NIS do responsável" text,
    "Endereço eletrônico do responsável" text,
    "Logradouro" text,
    "Número do logradouro" text,
    "Bairro do logradouro" text,
    "Complemento do logradouro" text,
    "Município do logradouro" text,
    "Distrito do logradouro" text,
    "UF do logradouro" text,
    "CEP do logradouro" text,
    "Número da conta de energia" text,
    "Latitude" text,
    "Longitude" text,
    "Localização diferenciada" text,
    "Rede de Escolas" text,
    "Código da escola" text,
    "Nome da escola" text,
    "Localização/Zona" text,
    "Etapa de ensino" text,
    "Modalidade" text,
    "Curso" text,
    "Série/Etapa" text,
    "Turno" text,
    "Turma" text,
    "Descrição da turma" text,
    "Nome do programa" text,
    "Tipo da turma" text,
    "Turma multietapa" text,
    "Turma multisseriada" text,
    "Situação da turma" text,
    "Número da sala" text,
    "Código do anexo" text,
    "Nome do anexo" text,
    "Número da matrícula do modelo novo da certidão" text,
    "Nacionalidade" text,
    "Remanescente de quilombo" text,
    "Pertencente ao povo cigano" text,

    CONSTRAINT staging_alunos_2026_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

ALTER TABLE public.staging_alunos_2026 OWNER to postgres;
